# Generated by Django 5.2.7 on 2025-11-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_extension', models.CharField(max_length=100)),
                ('direccion_extension', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Consulta', 'Consulta')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cohorte', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Cohorte')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20)),
                ('anio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.cohorte')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.especialidad')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.extension')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Copia de Cédula', 'Copia de Cédula'), ('Partida de Nacimiento Original', 'Partida de Nacimiento Original'), ('Fondo Negro Título', 'Fondo Negro Título'), ('Notas Originales', 'Notas Originales'), ('Copia de Planilla OPSU', 'Copia de Planilla OPSU'), ('Copia de Carnet Militar', 'Copia de Carnet Militar')], max_length=100)),
                ('estado_documento', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('Copia', 'Copia'), ('Vencida', 'Vencida'), ('Vacío', 'Vacío')], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiante')),
            ],
        ),
    ]
